Repository GDG-on-Campus-KHU/AOS-advanced-practice, pull requests merged in 2025-02, with the labels that each got.

#20 add Font
  app/src/main/java/com/example/bbip_clone/ui/theme/Font.kt
  app/src/main/java/com/example/bbip_clone/ui/theme/TextStyle.kt
  app/src/main/java/com/example/bbip_clone/ui/theme/Type.kt
  app/src/main/res/font/wantedsans_bold.ttf
  app/src/main/res/font/wantedsans_medium.ttf
  app/src/main/res/font/wantedsans_semibold.ttf
Labels: feature

#22 add color
  app/src/main/java/com/example/bbip_clone/ui/theme/Color.kt
Labels: feature

#21 create navigation bar
  app/src/main/java/com/example/bbip_clone/ui/TabBar.kt
Labels: feature, resource

#27 [Feat] Fix AppBar
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/bbip_clone/ui/AppBar.kt
  app/src/main/java/com/example/bbip_clone/ui/StudyHomeScreen.kt
  app/src/main/java/com/example/bbip_clone/ui/TabBar.kt
  app/src/main/java/com/example/bbip_clone/ui/UserHomeScreen.kt
  app/src/main/java/com/example/bbip_clone/ui/theme/TextStyle.kt
Labels: feature, resource

#29 [UI] StudyHomeMainImage
  app/src/main/java/com/example/bbip_clone/ui/StudyHomeScreen.kt
  app/src/main/res/drawable-nodpi/study_mask.png
Labels: resource

#30 [Feat] StudyNoticeView
  app/src/main/java/com/example/bbip_clone/Convert.kt
  app/src/main/java/com/example/bbip_clone/model/StudyWeek.kt
  app/src/main/java/com/example/bbip_clone/network/RetrofitClient.kt
  app/src/main/java/com/example/bbip_clone/ui/AppBar.kt
  app/src/main/java/com/example/bbip_clone/ui/CapsuleView.kt
  app/src/main/java/com/example/bbip_clone/ui/StudyHomeScreen.kt
  app/src/main/java/com/example/bbip_clone/ui/UserHomeScreen.kt
Labels: style, feature, resource

#31 [Feat] StudyInfoView & OptionsListView
  app/src/main/java/com/example/bbip_clone/Convert.kt
  app/src/main/java/com/example/bbip_clone/model/StudyWeekData.kt
  app/src/main/java/com/example/bbip_clone/model/WeekDate.kt
  app/src/main/java/com/example/bbip_clone/network/RetrofitClient.kt
  app/src/main/java/com/example/bbip_clone/ui/AppBar.kt
  app/src/main/java/com/example/bbip_clone/ui/CapsuleView.kt
  app/src/main/java/com/example/bbip_clone/ui/StudyHomeScreen.kt
  app/src/main/java/com/example/bbip_clone/ui/TabBar.kt
  app/src/main/java/com/example/bbip_clone/ui/theme/Icon.kt
  app/src/main/res/drawable-nodpi/archive.xml
  app/src/main/res/drawable-nodpi/attendance_certification.xml
  app/src/main/res/drawable-nodpi/check_location.xml
Labels: style, refactor, feature, resource

#32 [Feat] StudyProgressView
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/bbip_clone/Convert.kt
  app/src/main/java/com/example/bbip_clone/model/StudyWeekData.kt
  app/src/main/java/com/example/bbip_clone/ui/AppBar.kt
  app/src/main/java/com/example/bbip_clone/ui/CapsuleView.kt
  app/src/main/java/com/example/bbip_clone/ui/StudyHomeScreen.kt
  app/src/main/java/com/example/bbip_clone/ui/theme/TextStyle.kt
Labels: style, refactor, feature

#39 [Feat] Refresh & Animation & Image
  app/build.gradle.kts
  app/src/main/java/com/example/bbip_clone/ui/StudyHomeScreen.kt
  app/src/main/res/drawable-nodpi/study_mask.png
  app/src/main/res/drawable-nodpi/study_mask.xml
  gradle/libs.versions.toml
Labels: style, refactor, feature, resource

#41 [Feat] NoticeView
  app/src/main/java/com/example/bbip_clone/network/RetrofitClient.kt
  app/src/main/java/com/example/bbip_clone/ui/AppBar.kt
  app/src/main/java/com/example/bbip_clone/ui/CapsuleView.kt
  app/src/main/java/com/example/bbip_clone/ui/UserHomeScreen.kt
  app/src/main/java/com/example/bbip_clone/ui/theme/Text.kt
Labels: feature

#45 ThisWeekStudyView
  app/src/main/java/com/example/bbip_clone/model/ThisWeekStudyData.kt
  app/src/main/java/com/example/bbip_clone/network/RetrofitClient.kt
  app/src/main/java/com/example/bbip_clone/ui/CapsuleView.kt
  app/src/main/java/com/example/bbip_clone/ui/UserHomeScreen.kt
  app/src/main/java/com/example/bbip_clone/ui/theme/Color.kt
Labels: style, feature, resource

#46 UpcomingScheduleView
  app/src/main/java/com/example/bbip_clone/model/UpComingScheduleData.kt
  app/src/main/java/com/example/bbip_clone/network/RetrofitClient.kt
  app/src/main/java/com/example/bbip_clone/ui/CapsuleView.kt
  app/src/main/java/com/example/bbip_clone/ui/UserHomeScreen.kt
  app/src/main/java/com/example/bbip_clone/ui/theme/TextStyle.kt
  app/src/main/res/drawable/comingschedule1.png
  app/src/main/res/drawable/comingschedule2.png
  app/src/main/res/drawable/comingschedule3.png
  app/src/main/res/drawable/thisweekstudy1.png
Labels: style, feature, resource

#47 AppManualView
  app/src/main/java/com/example/bbip_clone/ui/UserHomeScreen.kt
  app/src/main/res/drawable/manual.png
Labels: feature, resource

#48 Add NoticeView & BulletinBoardView
  app/src/main/java/com/example/bbip_clone/ui/CapsuleView.kt
  app/src/main/java/com/example/bbip_clone/ui/StudyHomeScreen.kt
  app/src/main/java/com/example/bbip_clone/ui/UserHomeScreen.kt
Labels: refactor, feature
