Repository GDG-on-Campus-KHU/AOS-advanced-practice, pull requests merged in 2025-03, with the labels that each got.

#52 Reflect Reveiw&Feedback
  app/src/main/java/com/example/bbip_clone/ui/CapsuleView.kt
  app/src/main/java/com/example/bbip_clone/ui/UserHomeScreen.kt
Labels: style, refactor, feature, resource

#53 TabBar Update
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/bbip_clone/MainActivity.kt
  app/src/main/java/com/example/bbip_clone/NavigationGraph.kt
  app/src/main/java/com/example/bbip_clone/navigation/NavigationScreens.kt
  app/src/main/java/com/example/bbip_clone/navigation/TabNavigationGraph.kt
  app/src/main/java/com/example/bbip_clone/network/RetrofitClient.kt
  app/src/main/java/com/example/bbip_clone/ui/TabBar.kt
  app/src/main/java/com/example/bbip_clone/ui/TabBarScreen.kt
  app/src/main/res/drawable-mdpi/tab_bar.png
  app/src/main/res/drawable-nodpi/tabbar_center.xml
Labels: style, refactor

#55 Feat/#54
  app/src/main/java/com/example/bbip_clone/ui/CapsuleView.kt
  app/src/main/java/com/example/bbip_clone/ui/UserHomeScreen.kt
  app/src/main/res/drawable/attendance_ceritification_ellipse.png
  app/src/main/res/drawable/attendance_certification_tail_curve.png
  app/src/main/res/drawable/comingschedule1.png
  app/src/main/res/drawable/comingschedule1.xml
  app/src/main/res/drawable/comingschedule2.png
  app/src/main/res/drawable/comingschedule2.xml
  app/src/main/res/drawable/comingschedule3.png
  app/src/main/res/drawable/comingschedule3.xml
Labels: style, refactor, feature

#56 Update code refactoring
  app/src/main/java/com/example/bbip_clone/network/RetrofitClient.kt
  app/src/main/java/com/example/bbip_clone/ui/CapsuleView.kt
  app/src/main/java/com/example/bbip_clone/ui/StudyHomeScreen.kt
  app/src/main/java/com/example/bbip_clone/ui/UserHomeScreen.kt
Labels: style, refactor
